parameters:
#    sign_ips_player.example.class: SignIPS\PlayerBundle\Example

services:
#    sign_ips_player.example:
#        class: %sign_ips_player.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
